### ISSUE TITLE
Not loading on Xbox One

### ISSUE THREAD

**Issue by Azy77** [Aftnet/RetriX#2] opened 2018-05-28 16:29 UTC
Installed retrix 2.0.1.0 in Dev Mode on Xbox One with dependencies for x64. When loading retrix it returns to the main dev mode screen.

Also other Xbox One users have reported the same.

Many thanks for your help.

**Comment by albertofustinoni** [comment] 2018-05-28 22:52
Hello

I am aware of the issue and trying to figure out what’s wrong.
Hopefully a fix is coming soon

Alberto

From: Azy77
Sent: 29 May 2018 01:29
To: Aftnet/RetriX
Cc: Subscribed
Subject: [Aftnet/RetriX] Not loading on Xbox One (#2)

Installed retrix 2.0.1.0 in Dev Mode on Xbox One with dependencies for x64. When loading retrix it returns to the main dev mode screen.
Also Xbox One other users have reported the same.
Many thanks for your help.

**Comment by Azy77** [comment] 2018-05-29 14:26
That's great.

**Comment by dominater01** [comment] 2018-06-07 15:57
working just fine now thanks absestos 👍

**Comment by magicsgram** [comment] 2018-06-11 16:38
the gamepad doesn't work for snes on 2.0.2 on xbox one x?

**Comment by albertofustinoni** [comment] 2018-06-11 23:58
No, gamepad should work just fine on Xbox.

**Comment by magicsgram** [comment] 2018-06-12 11:08
@albertofustinoni It works fine for all other emulators except for the snes on xbox

**Comment by magicsgram** [comment] 2018-06-12 11:18
@albertofustinoni I just tested on Win10 x64. xbox controller doesn't work for snes here either:)
BTW, do you take PRs? I'd like to study the code base:)

**Comment by albertofustinoni** [comment] 2018-06-12 14:00
@magicsgram Just confirmed that input isn't working for snes.
I'd be more than glad for some help, so if you want to I'd be grateful :)

Since RetriX was becoming a bit too huge, I ended up splitting it between this repo and [LibRetriX](https://gitlab.com/aftnet/LibRetriX), which contains the interface code between RetriX and the Libretro cores it uses. Given that the issue is SNES specific, LibRetriX and Snes9X itself would be good places to start the investigation.

**Comment by albertofustinoni** [comment] 2018-06-14 23:47
Fixed Xbox issue, closing this

**Closed by albertofustinoni** 2018-06-14 23:47 UTC
